language: node_js
cache: npm
notifications:
  email:
    recipients:
      - $EMAIL_TOKEN
    on_success: always
    on_failure: always
node_js:
  - '10'

script:
  - yarn
  - yarn build
  - yarn deploy